apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirumahaja-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dirumahaja-service
  template:
    metadata:
      labels:
        app: dirumahaja-service
    spec:
      containers:
        - name: dirumahaja-service
          image: asia.gcr.io/miloo-phoenix/dirumahaja-rest
          ports:
            - containerPort: 3002

---

apiVersion: v1
kind: Service
metadata:
  name: dirumahaja-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: dirumahaja-service
  ports:
    - port: 8040
      targetPort: 3002
      name: dirumahaja-rest-port