export const COMMON_ERRORS = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
    TOKEN_INVALID: 'TOKEN_INVALID',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND'
};

export const SESSION_STATUS = {
    ON_GOING: 20,
    CLOSED: 30
};

export const EMBLEM_CODE = {
    HERO_ONE: 'HERO_ONE',
    HERO_TWO: 'HERO_TWO',
    WARRIOR_PANDEMI: 'WARRIOR_PANDEMI',
    KUCING_AJA_KALAH: 'KUCING_AJA_KALAH',
    PRINCESS_WABAH: 'PRINCESS_WABAH',
    AQUA_VIRUS: 'AQUA_VIRUS',
    CORONA_MAN: 'CORONA_MAN',
    CORONA_HEROES: 'CORONA_HEROES'
};
